export const levels = [
  {
    id: 1,
    name: '初识反射',
    cols: 8,
    rows: 8,
    emitter: { x: 0, y: 3, direction: 'RIGHT' },
    target: { x: 7, y: 3, direction: 'LEFT' },
    walls: [],
    preMirrors: [],
    maxMirrors: 0,
    hint: '激光直射目标，无需反光镜！',
  },
  {
    id: 2,
    name: '一面之缘',
    cols: 8,
    rows: 8,
    emitter: { x: 0, y: 3, direction: 'RIGHT' },
    target: { x: 3, y: 0, direction: 'DOWN' },
    walls: [],
    preMirrors: [],
    maxMirrors: 1,
    hint: '在路径上放置一面 / 型反光镜将激光向上反射',
  },
  {
    id: 3,
    name: '转角遇到光',
    cols: 8,
    rows: 8,
    emitter: { x: 0, y: 1, direction: 'RIGHT' },
    target: { x: 5, y: 6, direction: 'UP' },
    walls: [],
    preMirrors: [],
    maxMirrors: 2,
    hint: '使用两面反光镜完成 L 型路径',
  },
  {
    id: 4,
    name: '蛇形走位',
    cols: 8,
    rows: 8,
    emitter: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 0, y: 6, direction: 'RIGHT' },
    walls: [],
    preMirrors: [
      { x: 5, y: 0, type: '\\' },
    ],
    maxMirrors: 3,
    hint: '利用已有反光镜，添加三面完成蛇形路线',
  },
  {
    id: 5,
    name: '迷宫之光',
    cols: 8,
    rows: 8,
    emitter: { x: 0, y: 0, direction: 'RIGHT' },
    target: { x: 7, y: 7, direction: 'LEFT' },
    walls: [],
    preMirrors: [],
    maxMirrors: 4,
    hint: '规划一条穿越对角线的光路',
  },
  {
    id: 6,
    name: '反射大师',
    cols: 8,
    rows: 8,
    emitter: { x: 0, y: 7, direction: 'RIGHT' },
    target: { x: 7, y: 0, direction: 'LEFT' },
    walls: [],
    preMirrors: [
      { x: 3, y: 7, type: '/' },
    ],
    maxMirrors: 4,
    hint: '利用已有反光镜，完成对角线穿越',
  },
  {
    id: 7,
    name: '极限挑战',
    cols: 10,
    rows: 8,
    emitter: { x: 0, y: 4, direction: 'RIGHT' },
    target: { x: 9, y: 1, direction: 'LEFT' },
    walls: [],
    preMirrors: [],
    maxMirrors: 5,
    hint: '在更大的网格中规划复杂路径',
  },
  {
    id: 8,
    name: '终极试炼',
    cols: 10,
    rows: 10,
    emitter: { x: 0, y: 0, direction: 'DOWN' },
    target: { x: 9, y: 9, direction: 'LEFT' },
    walls: [],
    preMirrors: [
      { x: 0, y: 5, type: '\\' },
    ],
    maxMirrors: 6,
    hint: '最后的挑战！规划一条穿越整个棋盘的光路',
  },
]
