export const levels = [
  {
    id: 1,
    name: '初识反射',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 3, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 7, y: 3, direction: 'LEFT', color: 'red' }],
    walls: [],
    preElements: [],
    maxElements: 0,
    optimalElements: 0,
    hint: '激光直射目标，无需反光镜！',
    knowledgeId: null,
  },
  {
    id: 2,
    name: '一面之缘',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 3, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 3, y: 0, direction: 'DOWN', color: 'red' }],
    walls: [],
    preElements: [],
    maxElements: 1,
    optimalElements: 1,
    hint: '在路径上放置一面 / 型反光镜将激光向上反射',
    knowledgeId: 'reflection',
  },
  {
    id: 3,
    name: '转角遇到光',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 1, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 5, y: 6, direction: 'UP', color: 'red' }],
    walls: [],
    preElements: [],
    maxElements: 2,
    optimalElements: 2,
    hint: '使用两面反光镜完成 L 型路径',
    knowledgeId: null,
  },
  {
    id: 4,
    name: '蛇形走位',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 0, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 0, y: 6, direction: 'RIGHT', color: 'red' }],
    walls: [],
    preElements: [
      { x: 5, y: 0, type: '\\' },
    ],
    maxElements: 3,
    optimalElements: 3,
    hint: '利用已有反光镜，添加三面完成蛇形路线',
    knowledgeId: null,
  },
  {
    id: 5,
    name: '迷宫之光',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 0, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 7, y: 7, direction: 'LEFT', color: 'red' }],
    walls: [],
    preElements: [],
    maxElements: 4,
    optimalElements: 4,
    hint: '规划一条穿越对角线的光路',
    knowledgeId: null,
  },
  {
    id: 6,
    name: '反射大师',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 7, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 7, y: 0, direction: 'LEFT', color: 'red' }],
    walls: [],
    preElements: [
      { x: 3, y: 7, type: '/' },
    ],
    maxElements: 4,
    optimalElements: 3,
    hint: '利用已有反光镜，完成对角线穿越',
    knowledgeId: null,
  },
  {
    id: 7,
    name: '极限挑战',
    cols: 10,
    rows: 8,
    emitters: [{ x: 0, y: 4, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 9, y: 1, direction: 'LEFT', color: 'red' }],
    walls: [],
    preElements: [],
    maxElements: 5,
    optimalElements: 4,
    hint: '在更大的网格中规划复杂路径',
    knowledgeId: null,
  },
  {
    id: 8,
    name: '终极试炼',
    cols: 10,
    rows: 10,
    emitters: [{ x: 0, y: 0, direction: 'DOWN', color: 'red' }],
    targets: [{ x: 9, y: 9, direction: 'LEFT', color: 'red' }],
    walls: [],
    preElements: [
      { x: 0, y: 5, type: '\\' },
    ],
    maxElements: 6,
    optimalElements: 5,
    hint: '最后的挑战！规划一条穿越整个棋盘的光路',
    knowledgeId: null,
  },
  {
    id: 9,
    name: '分光之路',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 4, direction: 'RIGHT', color: 'red' }],
    targets: [
      { x: 7, y: 0, direction: 'LEFT', color: 'red' },
      { x: 7, y: 7, direction: 'LEFT', color: 'red' },
    ],
    walls: [],
    preElements: [],
    maxElements: 3,
    optimalElements: 2,
    hint: '分光镜可以将一束激光分成两束！一面反射一面穿过',
    knowledgeId: 'splitter',
    availableTypes: ['/', '\\', 'splitter'],
  },
  {
    id: 10,
    name: '色彩变换',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 4, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 7, y: 4, direction: 'LEFT', color: 'green' }],
    walls: [],
    preElements: [],
    maxElements: 2,
    optimalElements: 2,
    hint: '红色激光穿过绿色滤光片会变成绿色！滤光片不会改变方向',
    knowledgeId: 'filter',
    availableTypes: ['/', '\\', 'filter-green'],
  },
  {
    id: 11,
    name: '双色彩虹',
    cols: 10,
    rows: 8,
    emitters: [
      { x: 0, y: 2, direction: 'RIGHT', color: 'red' },
      { x: 0, y: 6, direction: 'RIGHT', color: 'red' },
    ],
    targets: [
      { x: 9, y: 2, direction: 'LEFT', color: 'red' },
      { x: 9, y: 6, direction: 'LEFT', color: 'green' },
    ],
    walls: [],
    preElements: [],
    maxElements: 4,
    optimalElements: 3,
    hint: '两束红色激光，一束保持红色，另一束通过滤光片变绿色',
    knowledgeId: null,
    availableTypes: ['/', '\\', 'filter-green', 'filter-blue'],
  },
  {
    id: 12,
    name: '光纤穿越',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 4, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 7, y: 4, direction: 'LEFT', color: 'red' }],
    walls: [],
    preElements: [
      { x: 3, y: 4, type: 'fiber-in', pairId: 'f1' },
      { x: 5, y: 4, type: 'fiber-out', pairId: 'f1', direction: 'RIGHT' },
    ],
    maxElements: 2,
    optimalElements: 1,
    hint: '光纤入口接收激光，从出口传出！中间的障碍不再是问题',
    knowledgeId: 'fiber',
    availableTypes: ['/', '\\'],
  },
  {
    id: 13,
    name: '透镜聚焦',
    cols: 8,
    rows: 8,
    emitters: [{ x: 0, y: 3, direction: 'RIGHT', color: 'red' }],
    targets: [{ x: 7, y: 3, direction: 'LEFT', color: 'red' }],
    walls: [],
    preElements: [
      { x: 4, y: 3, type: 'lens' },
    ],
    maxElements: 2,
    optimalElements: 2,
    hint: '透镜让激光直线穿过不改变方向，但可以搭配反光镜使用',
    knowledgeId: 'lens',
    availableTypes: ['/', '\\'],
  },
  {
    id: 14,
    name: '光谱大师',
    cols: 10,
    rows: 10,
    emitters: [
      { x: 0, y: 2, direction: 'RIGHT', color: 'red' },
      { x: 0, y: 5, direction: 'RIGHT', color: 'red' },
      { x: 0, y: 8, direction: 'RIGHT', color: 'red' },
    ],
    targets: [
      { x: 9, y: 2, direction: 'LEFT', color: 'red' },
      { x: 9, y: 5, direction: 'LEFT', color: 'green' },
      { x: 9, y: 8, direction: 'LEFT', color: 'blue' },
    ],
    walls: [],
    preElements: [],
    maxElements: 8,
    optimalElements: 6,
    hint: '三束激光需要三种颜色！灵活运用滤光片和反光镜',
    knowledgeId: null,
    availableTypes: ['/', '\\', 'splitter', 'filter-red', 'filter-green', 'filter-blue', 'lens'],
  },
]
